# Generated by Django 5.2.7 on 2026-07-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Abonné', 'verbose_name_plural': 'Abonnés'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Abonné le'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
