# Generated by Django 5.2.7 on 2025-12-05 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse admin'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
